create table if not exists public.person_responsibility_scopes (
    scope_id bigint generated by default as identity primary key,
    person_id bigint not null references public.persons(person_id) on delete cascade,
    scope_type varchar(32) not null check (scope_type in ('department', 'city', 'department_city', 'location')),
    department varchar(255),
    city varchar(255),
    location_id bigint references public.locations(location_id) on delete set null,
    is_active boolean not null default true,
    notes text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint person_responsibility_scopes_scope_required check (
        (scope_type = 'department' and department is not null)
        or (scope_type = 'city' and city is not null)
        or (scope_type = 'department_city' and department is not null and city is not null)
        or (scope_type = 'location' and location_id is not null)
    )
);

create index if not exists idx_person_responsibility_scopes_person_id
    on public.person_responsibility_scopes(person_id);

create index if not exists idx_person_responsibility_scopes_active
    on public.person_responsibility_scopes(is_active);

create index if not exists idx_person_responsibility_scopes_location_id
    on public.person_responsibility_scopes(location_id);
